package diplomat

import (
	"html/template"
	"log"
)

type TranslationPair struct {
	Key        string
	Translated string
}

type MessengerConfig struct {
	Type    string
	Options YAMLOption
}

type BasicMessengerConfig struct {
	messengerType string
	name          string
	content       LocaleTranslations
	locale        string
	fragmentName  string
}

func (c BasicMessengerConfig) GetType() string {
	return c.messengerType
}

func (c BasicMessengerConfig) GetName() string {
	return c.name
}

func (c BasicMessengerConfig) GetContent() LocaleTranslations {
	return c.content
}

func (c BasicMessengerConfig) GetLocale() string {
	return c.locale
}

func (c BasicMessengerConfig) GetFragmentName() string {
	return c.fragmentName
}

var JsMessengerTemplate *template.Template

func init() {
	var err error
	JsMessengerTemplate, err = template.New("jsMessengerTemplate").Parse(`// DO NOT EDIT. generated by diplomat (https://github.com/MinecraftXwinP/diplomat).
export default {
    {{- range $k,$v := . }}
    {{$k}}: "{{$v}}",
{{ end -}}
}
`)
	if err != nil {
		log.Fatal(err)
	}
}

func NewJsModuleMessenger(config MessengerConfig) *jsModuleMessenger {
	return &jsModuleMessenger{config}
}

type jsModuleMessenger struct {
	config MessengerConfig
}

func (j jsModuleMessenger) GetFolder() string {
	return "js"
}
