package javascript

import (
	"fmt"
	"github.com/insufficientchocolate/diplomat/pkg/parser/yaml"
)

const source = `
control_panel:
  start:
    zh-TW: 開始
    en: Start
  pause:
    zh-TW: 暫停
    en: Pause
`

func ExampleObjectEmitter_Emit() {
	parser := yaml.NewParser([]byte(source))
	translation, err := parser.GetTranslation()
	if err != nil {
		panic(err)
	}
	emitter := NewObjectEmitter()
	output, err := emitter.Emit(translation)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(output))
	// Output:
	//// DO NOT EDIT. generated by diplomat (https://github.com/insufficientchocolate/diplomat).
	//export default {
	//".control_panel.start.zh-TW": "開始",".control_panel.start.en": "Start",".control_panel.pause.zh-TW": "暫停",".control_panel.pause.en": "Pause",
	//}
}
