package javascript

import (
	"github.com/insufficientchocolate/diplomat/pkg/data"
	"github.com/insufficientchocolate/diplomat/pkg/emit"
)

const javascriptTemplate = `// DO NOT EDIT. generated by diplomat (https://github.com/insufficientchocolate/diplomat).
export default {
{{ range .Pairs -}}
    "{{ JoinKeys .Key "." }}": "{{ .Text }}",
{{- end }}
}`


type ObjectEmitter struct {
	*emit.TemplateEmitter
}

func (o ObjectEmitter) Emit(translation data.Translation) ([]byte,error) {
	return o.TemplateEmitter.Emit(translation)
}

func NewObjectEmitter() *ObjectEmitter {
	templateEmitter, err := emit.NewTemplateEmitter(javascriptTemplate)
	if err != nil {
		panic(err)
	}
	return &ObjectEmitter{
		templateEmitter,
	}
}

func init() {
	emit.GlobalRegistry.Registry("js-object", NewObjectEmitter())
}


